---
name: module4_task0

on:
  schedule:
    - cron: "30 22 * * 0-6"
  push:
    paths:
      - "Docker/module4_task0/**"
    branches:
      - "main"
      - "master"
    pull_request:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Validate if setup.sh have erros
        env:
          PATH: "$(PATH):/$(go env GOPATH)/bin"
        run: |
          make -C Docker/module4_task0 lint

      - name: Setup the app
        run: |
          cd Docker/module4_task0
          sudo ./setup.sh

      - name: Build the app
        run: |
          make -C Docker/module4_task0 build

      - name: Build and create the package
        run: |
          make -C Docker/module4_task0 package

      - name: Build report for the operation team
        uses: actions/upload-artifact@v3
        with:
          name: build-report
          path: |
            Docker/module4_task0/awesome-website.zip
            Docker/module4_task0/DEPLOY.md

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Docker/module4_task0/awesome-website.zip
            Docker/module4_task0/DEPLOY.md

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "./Docker/module4_task0/dist"
          production-branch: main
          github-token: ${{ secrets.REPO_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
