---
name: module3_task2
on:
  push:
    branches:
      - 'main'
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Clone the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Go to the right directory
        run: cd CI_CD/module3_task2

      - name: Scan the directory
        run: ls -R

      - name: Setup the app
        run: |
          cd CI_CD/module3_task2
          sudo ./setup.sh

      - name: Validate if setup.sh have erros
        run: |
          make -C CI_CD/module3_task2 lint

      - name: Build the app
        run: |
          make -C CI_CD/module3_task2 build

      - name: Saves the dist directory
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist/

      - name: Loads the dist directory
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: |
            CD_CD/module_3_task2/

      - name: Build and create the package
        run: |
          make -C CI_CD/module3_task2 package

      - name: Build report for the operation team
        uses: actions/upload-artifact@v3
        with:
          name: build-report
          path: |
            CI_CD/module3_task2/awesome-website.zip
            CI_CD/module3_task2/DEPLOY.md
...
