---
name: module3_task1
on:
  schedule:
    - cron: "30 22 * * 0-6"
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Clone the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Validate if setup.sh have erros
      - run: make -C CI_CD/module3_task1 lint

      - name: Setup the app
      - run: cd CI_CD/module3_task1 && sudo ./setup.sh

      - name: Build the app
      - run: make -C CI_CD/module3_task1 build
...
