---
name: module3_task0
on:
  push:
    paths:
      - "CI_CD/module3_task0/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test the help command
        run: make -C CI_CD/module3_task0 help
