---
name: module3_task0
on:
  schedule:
    - cron: "30 22 * * 0-6"
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Clone the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test the help command
      - run: make -C CI_CD/module3_task0 help
...
