---
name: module3_task0
on:
  schedule:
    - cron: "30 22 * * 0-6"
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test the help command
        uses: actions/checkout@v3
      - run: cd CI_CD/module3_task0 && make help
...
