---
name: module3_task1
on:
  schedule:
    - cron: "30 22 * * 0-6"
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup the app
        uses: actions/checkout@v3
      - run: cd CI_CD/module3_task1 && sudo ./setup.sh

      - name: Validate if setup.sh have erros
        uses: actions/checkout@v3
      - run: cd CI_CD/module3_task1 && make lint

      - name: Build the app
        uses: actions/checkout@v3
      - run: cd CI_CD/module3_task1 && make build
...